name: Build Images

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: v1.0.0

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build Server AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/s3-mirror:${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build Server ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/s3-mirror:${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Create Server multi-arch manifest
        run: |
          docker buildx imagetools create -t registry.cn-qingdao.aliyuncs.com/wod/s3-mirror:${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/s3-mirror:${{ env.BUILD_VERSION }}-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/s3-mirror:${{ env.BUILD_VERSION }}-arm64
